### ISSUE TITLE
Robotbuilder drive code example crashes

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/RobotBuilder#467]
When following the RobotBuilder documentation for driving with joysticks on frc-docs, the example code crashes with a null pointer exception for getting the joysticks. https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/robotbuilder/writing-code/robotbuilder-drive-tank.html

```
Error at frc.robot.commands.TankDrive.<init>(TankDrive.java:32): Unhandled exception: java.lang.NullPointerException
        at frc.robot.commands.TankDrive.<init>(TankDrive.java:32)
        at frc.robot.RobotContainer.<init>(RobotContainer.java:90)
        at frc.robot.RobotContainer.<clinit>(RobotContainer.java:38)
        at frc.robot.Robot.robotInit(Robot.java:43)
        at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:107)
        at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:373)
        at edu.wpi.first.wpilibj.RobotBase.lambda$startRobot$0(RobotBase.java:443)
        at java.base/java.lang.Thread.run(Thread.java:829)

Warning at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:388): The robot program quit unexpectedly. This is usually due to a code error.
  The above stacktrace can help determine where the error occurred.
  See https://wpilib.org/stacktrace for more information.
Error at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:395): The startCompetition() method (or methods called by it) should have handled the exception above.
```

**Comment by sciencewhiz** [comment]
fixed by wpilibsuite/frc-docs#1739
